name: Run Commands

on:
  push
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
        id: Run_script

      - name: Run a multi-line script
        run: |
          git config user.name "ap185428"
          git config user.email "ap185428@ncr.com"
          pwd
          git status
          touch hello.txt
          git status
          git add .
          git status
          git commit -m "new file created"
          git status         
          python3 test.py
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: public/  
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@main
      with: 
        name: webpack artifacts
        path: public
    - run: |
        git status

  
